# -*- coding: utf-8 -*-
"""B21CH025

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16h7PDxOlReAVTrBXWORAjrDIu72ZVQZS
"""

import pandas as pd
df = pd.read_csv('/content/drive/MyDrive/Classroom/IML (July 2022)/Superstore.csv', encoding='windows-1252')

df.head()

df.describe()

df.info()

from google.colab import drive
drive.mount('/content/drive')

"""Question 2"""

import numpy as np
a = np.linspace(0, 2, 6)

a

c = a.mean()  # To find mean of array
print("mean" , c)
d = a.std()   # To find Standard Deviation of array
print("Standard Deviation" , d)

b = np.array([[0,1,2], [3,4,5] , [6,9,8]])   # Generate a random 3x3 matrix

print(b)
det = np.linalg.det(b)  # To find determinant of matrix

print("Determinant of matrix is" ,det)

inverse = np.linalg.inv(b)   # To find inverse of matrix

print("Inverse of matrix is" ,inverse)

w, v = np.linalg.eig(b)  # To find eigenvalues and eigenvectors of matrix

print("Eigenvalues of matrix are" , w)

print("Eigenvectors of matrix are" , v)

